### ISSUE TITLE
Student Login/ Logout authentication

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#1]
Student Schema parameters:

- `student Name`
- `password`
- `School name`

Initial routes:

1. `/v1/student/login` - to login the student 
2. `/v1/student/logout` - for logging out the user

_Note_: All function, variable and file names should contain **camel-case** notation.

**Comment by realsh9dy** [comment]
Hello, do i just have to create the login page?

**Comment by realsh9dy** [comment]
Can you assign me this issue.

**Comment by realsh9dy** [comment]
Just provide me the jist of what do you expect and as I'm a beginner can you please give me a heads up.

**Comment by gangLocust42** [comment]
I want to work on this issue under JWOC? And please brief me about user model you have planed.

**Comment by adityakhattri21** [comment]
I would like to work on this issue and design the API for your project.

**Comment by Anshkanungo** [comment]
Hey, i would like to contribute to login page under JWOC, i have some prior experience in building login authentication and authorisation page and logout page.

**Comment by Gaurav-Verma07** [comment]
> I want to work on this issue under JWOC? And please brief me about user model you have planed.

Hey Akshat, I've updated the required fields for userSchema, please go through it.

**Comment by Gaurav-Verma07** [comment]
> Just provide me the jist of what do you expect and as I'm a beginner can you please give me a heads up.

I'll open a beginner friendly issue `register student` soon
