### ISSUE TITLE
Wraps controllers into global error handling middleware

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#12]
Wrap all the controllers in global `catchAsync` middleware which is a **Higher Order Function**.
`catchAsync` is defined in `utils` folder.
**Test** all the controller functionalities after wraping.

An example for the same is attached.

![image](https://user-images.githubusercontent.com/63046396/219856990-937180bb-7a5f-4742-af29-d2d72ad3034d.png)

**Comment by TuhinBanerjee31** [comment]
Can I get assigned to this issue under JWOC ?

**Comment by Gaurav-Verma07** [comment]
Resolved with PR #16
