### ISSUE TITLE
Assignment submission teacher side

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#13]
dataModal:

- `subject`
- `teacher` - mongooseID
- `class`
- `assignmentInfo`
- `assignedDate`
- `isDocumentFormat` - check if document is attached
- `assignment` - related attached document 
- `lastDate`

`/v1/teacher/assignment` - to post assignments

**Comment by SHAIKASIFALI** [comment]
I would like to work on this issue can u please assign me this issue

**Comment by sayandippaul** [comment]
i want to work on this issue pls assign me

**Comment by Gaurav-Verma07** [comment]
@sayandippaul  any updates??

**Comment by SHAIKASIFALI** [comment]
will update u till tomoroow evening

**Comment by sayandippaul** [comment]
yeah i am working on that 
trying to submit by tommorow

**Comment by Gaurav-Verma07** [comment]
Brother, any updates???

**Comment by SHAIKASIFALI** [comment]
can u please assign this issue to me i want to work on it

**Comment by SHAIKASIFALI** [comment]
bro do i need to create a new model or there is any model existingto which i can use

**Comment by SHAIKASIFALI** [comment]
what do i need to store in the assignment ..do i need to store the path to the pdf .. uplaoded by the teacher

**Comment by Gaurav-Verma07** [comment]
Yes, store the pdf file in the database.
Sorry couldn't reply.... was busy with work.

**Comment by Gaurav-Verma07** [comment]
hey, updates??

**Comment by sayandippaul** [comment]
Unassign it from me
My phone got stolen previous week
I am busy in official lettering and sim retrieve
Sorry

**Comment by Gaurav-Verma07** [comment]
@sayandippaul , okk bro. Take care.

**Comment by Laxmankohar** [comment]
@Gaurav-Verma07 , I want to work on this issue under JWOC. Can you please assign it to me?

**Comment by SHAIKASIFALI** [comment]
@Gaurav-Verma07 bro i want to make pr today but u have unassigned me without .. any prior intimation

**Comment by SHAIKASIFALI** [comment]
you have replied yesterday bro regarding it ..i am working on it now and have done with uploading just checking whethers its working fine or not but u have unassigned ,,

**Comment by Gaurav-Verma07** [comment]
@SHAIKASIFALI , my bad bro. I thought it was you asking to **unassign the issue**

**Comment by SHAIKASIFALI** [comment]
@Gaurav-Verma07  its ok bro

**Comment by Gaurav-Verma07** [comment]
Issue resolved PR #29
