### ISSUE TITLE
Student details from administration

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#14]
Get student data from admin as **excel** or **csv **  format (files).
Extract the info and store as studentOfficial info.

dataModal:
- `dataFile` - data uploaded by admin
- `class` - associated class
- `batchYear` - year of present associated class
- `date` - uploaded date

`/v1/admin/postStudentData` - to post student data

**Comment by SHAIKASIFALI** [comment]
I would like to work on this issue under jwoc can u please assign me this issue

**Comment by Gaurav-Verma07** [comment]
@SHAIKASIFALI  any updates??

**Comment by SHAIKASIFALI** [comment]
will update u tomorrow morning ..

**Comment by SHAIKASIFALI** [comment]
Need onehelp what to send as datafile ..in api is itsonething url like link

**Comment by SHAIKASIFALI** [comment]
can u please elaborate and give one example ,..

**Comment by Gaurav-Verma07** [comment]
Admin will send excel file to the server. Do not use any file link as data form.
Use **multer** to handle file at server.
Go through this [article](https://medium.com/sliitwif/import-excel-data-to-the-mongodb-database-d217761300cc)

Utilize the newStudent Model to store extracted data from excel file.

While testing make sure to choose `form-data` as body type 

![image](https://user-images.githubusercontent.com/63046396/220424365-a1b7088a-20ff-4dbb-949c-e2db20ec0138.png)


For now the required fields in .xlsx file:
![image](https://user-images.githubusercontent.com/63046396/220423212-308f1dda-fa4e-44cc-b286-499dec2a67e7.png)

**Comment by Gaurav-Verma07** [comment]
Issue resolved with PR #19
