### ISSUE TITLE
Setup eslint and prettier in server directory

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#15]

**Comment by Laxmankohar** [comment]
Hey @Gaurav-Verma07 , I would like to work on this issue under JWOC. Can you assign it to me?

**Comment by Laxmankohar** [comment]
Hey @Gaurav-Verma07 , I want to know that eslint and prettier will only work on server directory not in client directory.

**Comment by Gaurav-Verma07** [comment]
Yes, since our major focus for now is server dir.

**Comment by Laxmankohar** [comment]
Bro, checkout the rules. is it ok or not?

![image](https://user-images.githubusercontent.com/73365025/220548905-bdaa31c7-32b5-428e-940e-e74b729d42a3.png)

**Comment by Laxmankohar** [comment]
@Gaurav-Verma07 , Please check it and confirm sothat i can make a pull request..

![image](https://user-images.githubusercontent.com/73365025/220621225-1b58706c-54fe-4f6d-8828-024885033b54.png)
![image](https://user-images.githubusercontent.com/73365025/220621232-955f281f-40db-4800-a02f-6f7dc8801561.png)

**Comment by Laxmankohar** [comment]
There is only two branch showing main and refactor. it is not showing task/eslint-pr-commit branch, how can i fetch it?

![image](https://user-images.githubusercontent.com/73365025/221281021-593c00d5-b11a-4ed8-ac94-63c7ab454a60.png)

**Comment by Gaurav-Verma07** [comment]
#24
