### ISSUE TITLE
improve the designing by  making changes in the css file

### ISSUE THREAD

**Issue by Code1705** [Gaurav-Verma07/school-erp-system#17]

**Comment by Gaurav-Verma07** [comment]
Please explain as what changes we are primarily discussing here like since we don't have any significant css file.

**Comment by Code1705** [comment]
Background colour ,fonts, styling in the index.css file.

**Comment by Gaurav-Verma07** [comment]
I think `index.css` is in sync with mantine changing might led to overlapping classes.

**Comment by Gaurav-Verma07** [comment]
Using your idea I've opened a refactoring issue #18, check that out and comment if want to get assigned.
