### ISSUE TITLE
Refactor styles in component of admin and client directory

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#18]
Remove `useStyles` from .tsx files (component) to `styles.ts` in the same component folder.
Use **HomeNavbar** folder as reference.

![image](https://user-images.githubusercontent.com/63046396/220436976-20ef9183-0d9a-4d63-82a8-7013569bd063.png)

**Comment by Laxmankohar** [comment]
@Gaurav-Verma07 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by Laxmankohar** [comment]
@Gaurav-Verma07 bro, Is it ok?

![image](https://user-images.githubusercontent.com/73365025/221199182-cfcbb7a0-4375-4e50-b9db-a3dbbab64e3f.png)
![image](https://user-images.githubusercontent.com/73365025/221199692-edb674d2-3243-400f-b71b-70aa3ab84ad9.png)

**Comment by Gaurav-Verma07** [comment]
Yeah, it's cool

**Comment by Laxmankohar** [comment]
Can i make a pull request by updating Readme and .all-contributorsrc?

**Comment by Gaurav-Verma07** [comment]
yep

**Comment by Gaurav-Verma07** [comment]
Resolved with PR #25
