### ISSUE TITLE
Activate logOut Button by creating a logOut Function #2

### ISSUE THREAD

**Issue by Anshkanungo** [Gaurav-Verma07/school-erp-system#2]
Create a function to delete cookies and send user back to Login page.

**Comment by Anshkanungo** [comment]
I want to work on this issue under JWOC 2023.

**Comment by nisKULDEEP** [comment]
is this open issue? can you assign this to me

**Comment by sayandippaul** [comment]
i want to work under this issue

**Comment by Gaurav-Verma07** [comment]
This issue has been resolved under PR #6
