### ISSUE TITLE
Teachers details from administration

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#27]
Get teachers data from admin as excel or **csv ** format (files).
Extract the info and store as teachersOfficial info.

dataModal:

`dataFile`- data uploaded by admin
`date` - uploaded date

`/v1/admin/postTeachersData` - to post teachers data

**Comment by Laxmankohar** [comment]
I want to work on this issue under JWOC. Can you please assign it to me?

**Comment by Laxmankohar** [comment]
Bro, which model should i used  for data to be stored in this case or i have to create a new model for the teacher?

**Comment by Gaurav-Verma07** [comment]
I'll provide it by tomorrow

**Comment by Gaurav-Verma07** [comment]
for now continue with this.
For testing create fake data online.

![image](https://user-images.githubusercontent.com/63046396/221779724-3c0dd513-d9e5-4038-be0b-2dd4a6b913a1.png)

**Comment by Laxmankohar** [comment]
> for now continue with this. For testing create fake data online.
> 
> ![image](https://user-images.githubusercontent.com/63046396/221779724-3c0dd513-d9e5-4038-be0b-2dd4a6b913a1.png)

Should i have to create a new model with the given data?

**Comment by Gaurav-Verma07** [comment]
yes
teacherModal.js

Make the **appointDate** to be `MM/YYYY` format.

**Comment by Laxmankohar** [comment]
I am getting this error why and how can i resolve it?

![image](https://user-images.githubusercontent.com/73365025/221888188-31aec29d-6355-4ec0-a574-875b030706cc.png)
![image](https://user-images.githubusercontent.com/73365025/221888405-72899aec-08a6-4659-bc81-350fb9927a5b.png)

**Comment by Gaurav-Verma07** [comment]
Show me the modal you created and also your testing request data.
It's a casting error, somewhere **boolean** is used instead of **string** or vice verse.

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/221895668-e7cc9ea9-2f72-42eb-a8b4-40b2891e2ff7.png)
![image](https://user-images.githubusercontent.com/73365025/221895914-432edc9e-5f02-4bcc-8116-4c0c1d9e5aee.png)

**Comment by Gaurav-Verma07** [comment]
share this .xlsx file

**Comment by Laxmankohar** [comment]
[TeacherData1.xlsx](https://github.com/Gaurav-Verma07/school-erp-system/files/10851859/TeacherData1.xlsx)

**Comment by Gaurav-Verma07** [comment]
The fact that spreadSheet converts **TRUE** to string if not specified and it would troublesome to define **type** for every value in sheet. There must be some ways around it but since we are not aware about it, do one thing. 
Change **true or false** in sheet to 0 or 1 and then manually check the value, if 1 then true otherwise false.

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/221901242-a36e9e58-2d6c-45da-b611-cc05d2344706.png)

**Comment by Laxmankohar** [comment]
it is working  while using 0 and 1

**Comment by Gaurav-Verma07** [comment]
Great bro 😊.
Since I haven't worked much with excel files so couldn't help much.
Its nice that you figured out yourself.

**Comment by Laxmankohar** [comment]
> Great bro 😊. Since I haven't worked much with excel files so couldn't help much. Its nice that you figured out yourself.

Same bro. i have also never worked with excel files

**Comment by Laxmankohar** [comment]
Is it ok ?
![image](https://user-images.githubusercontent.com/73365025/221906658-22b545e2-8f10-4629-a5b1-426c9a99b1da.png)

**Comment by Laxmankohar** [comment]
Should i make a PR?

**Comment by Gaurav-Verma07** [comment]
Sure

**Comment by Gaurav-Verma07** [comment]
Resolved with PR #28
