### ISSUE TITLE
Student Registration

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#3]
userModal for student:

- `Student Name`
- `Class`
- `Section`
- `Roll Number`
- `Father's Name`
- `Mother's Name`
- `School Name`

`/v1/register` - route to register the student.

Create userSchema, routes and controllers for registering new student in the application

**Comment by Laxmankohar** [comment]
Hey @Gaurav-Verma07 I would like to work on this issue under JWOC. Can You please assign it to me?

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by Gaurav-Verma07** [comment]
> can u assign me this issue

Hey please go through issue #5 , you may work on that.

**Comment by Laxmankohar** [comment]
Hey @Gaurav-Verma07 , I want to know that i only have to create the backend for the registration page?

**Comment by Gaurav-Verma07** [comment]
> Hey @Gaurav-Verma07 , I want to know that i only have to create the backend for the registration page?

yep only the Backend

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/219657980-9b40c4cf-41ca-4bd2-83ee-0be63adb81e9.png)
![image](https://user-images.githubusercontent.com/73365025/219657992-20d6afbc-3d1e-4b7c-8001-ce30fa18cb68.png)
![image](https://user-images.githubusercontent.com/73365025/219658009-3131f2db-d0d9-4699-a5d3-4b7dceeadc3b.png)
![image](https://user-images.githubusercontent.com/73365025/219658023-ce7cf246-5c85-4d65-9354-e07c66ebb94a.png)



Why the response page is blank, ti should give some output. and in every response  i get index.html page.

**Comment by Gaurav-Verma07** [comment]
@Laxmankohar , try `http://localhost:3000/v1`
I'm getting the response in **postman**

![image](https://user-images.githubusercontent.com/63046396/219711283-0d6715ff-3070-40fa-81e5-e44e78df1cc6.png)

**Comment by Gun2902** [comment]
Sure I ll do that thank u brother for assign me this issue

**Comment by Laxmankohar** [comment]
@Gaurav-Verma07 , Please have a look bro.

![image](https://user-images.githubusercontent.com/73365025/219830690-c84968e0-7b22-4ea6-95cf-8ce947870345.png)

**Comment by Gaurav-Verma07** [comment]
@Laxmankohar cool bhai.

**Comment by Laxmankohar** [comment]
So, I am going make a pull request.

**Comment by Gaurav-Verma07** [comment]
Resolved with PR #11
