### ISSUE TITLE
Administrative Notice Board 

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#5]
Build APIs for student dashboard- 

dataModal: 

- `Topic`
- `Title`
- `Description`
- `Body`
- `Date Published`
- `isImportant`

routes for required APIs:
`/v1/notice/post`- to add new notice
`/v1/notice/all` - to get all notices
`/v1/notice/:id` - to get a particular notice by its ID.

**Comment by Sar-thak-3** [comment]
I want to work on this issue, kindly assign it to me!

**Comment by Gaurav-Verma07** [comment]
Issue resolved under PR #9
