### ISSUE TITLE
Student Attendence

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#8]
dataSchema:

- `Teacher name`
- `Student ID` - mongooseID
- `subject`
- `date`
- `No. of periods`

routes:

`/v1/teacher/post` - to post new attendence
`/v1/student/attendence/all` - to view all attendence
`/v1/student/attendence/:subject` - to get attendence of a particular subject

**Comment by Sar-thak-3** [comment]
I'm interested, kindly assign it to me!

**Comment by gangLocust42** [comment]
I want to work on this issue under JWOC.

**Comment by Gaurav-Verma07** [comment]
Resolved with PR #10
